name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v6

      - name: 'Setup node'
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm

      - name: 'Install'
        run: pnpm install

      - name: 'Build'
        run: pnpm build

      - name: 'Configure pages'
        uses: actions/configure-pages@v6

      - name: 'Upload pages artifact'
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy to Github Pages'
        id: deployment
        uses: actions/deploy-pages@v5
